// Test data factories — mirror the shape the synced API actually returns
// (server/utils/feedItems.ts → FeedItemResult), NOT the retired mock.js. The
// mock-only card fields (text/meta/excerpt/views/thumb/progress) are gone on
// purpose: real feeds never carry them, so cards must render without them.

export const makeArticle = (overrides: Record<string, unknown> = {}) => ({
  id: 1,
  feedId: 10,
  guid: "article-guid-1",
  type: "article",
  source: "Test Source",
  handle: "test.example.com",
  title: "Test Article Title",
  time: "2h",
  tags: ["design", "web"],
  unread: true,
  saved: false,
  starred: false,
  url: "https://test.example.com/article-1",
  author: "Test Author",
  imageUrl: null,
  content: "First paragraph.\n\nSecond paragraph.",
  mediaUrl: null,
  mediaDuration: null,
  ...overrides,
});

export const makeVideo = (overrides: Record<string, unknown> = {}) => ({
  id: 2,
  feedId: 20,
  guid: "video-guid-1",
  type: "video",
  source: "Test Channel",
  handle: "@testchannel",
  title: "Test Video Title",
  time: "1d",
  tags: null,
  unread: false,
  saved: false,
  starred: false,
  url: "https://www.youtube.com/watch?v=test123",
  author: "Test Channel",
  imageUrl: "https://example.com/thumb.jpg",
  content: "Full video description here.",
  mediaUrl: null,
  mediaDuration: 754,
  ...overrides,
});

export const makeTweet = (overrides: Record<string, unknown> = {}) => ({
  id: 3,
  feedId: 30,
  guid: "tweet-guid-1",
  type: "tweet",
  source: "Test User",
  handle: "@testuser",
  title: "This is a test tweet body text.",
  time: "3h",
  tags: null,
  unread: true,
  saved: false,
  starred: false,
  url: "https://bsky.app/profile/testuser/post/1",
  author: "Test User",
  imageUrl: null,
  content: "This is a test tweet body text.",
  mediaUrl: null,
  mediaDuration: null,
  ...overrides,
});

export const makePodcast = (overrides: Record<string, unknown> = {}) => ({
  id: 4,
  feedId: 40,
  guid: "podcast-guid-1",
  type: "podcast",
  source: "Test Podcast",
  handle: "podcast.example.com",
  title: "Test Episode Title",
  time: "1d",
  tags: null,
  unread: false,
  saved: false,
  starred: false,
  url: "https://podcast.example.com/episode-1",
  author: "Test Podcast",
  imageUrl: "https://example.com/cover.jpg",
  content: "Show note one.\n\nShow note two.",
  mediaUrl: "https://podcast.example.com/episode-1.mp3",
  mediaDuration: 2700,
  ...overrides,
});

export const makeFeed = (overrides: Record<string, unknown> = {}) => ({
  id: "f1",
  type: "rss",
  name: "Test Feed",
  url: "test.example.com/feed.xml",
  count: 5,
  color: "var(--src-rss)",
  status: "ok",
  ...overrides,
});

export const makeConnection = (overrides: Record<string, unknown> = {}) => ({
  id: "youtube",
  name: "YouTube",
  desc: "Subscribe to channels",
  connected: false,
  account: "",
  color: "var(--src-video)",
  since: "",
  needsReconnect: false,
  syncError: null,
  ...overrides,
});
